config/routes.rb
MorduBear::Application.routes.draw do

  get "cars/new"
  resources :spare_parts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "static_pages/preoperation"
  get "static_pages/operation"
  get "static_pages/administration"

  root  'sessions#new'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/new_spare_part', to: 'spare_parts#new', via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_one :brand
  has_many :workshop_cars
  has_and_belongs_to_many :spare_parts
end

app/models/spare_part.rb
class SparePart < ActiveRecord::Base
  has_many :stock_spare_parts
  has_and_belongs_to_many :cars
end

app/models/stock_spare_part.rb
class StockSparePart < ActiveRecord::Base
  belongs_to :workshop_car
  belongs_to :spare_part
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :lastname,  presence: true
  validates :permissions,  presence: true
  has_secure_password
  validates :password, length: { minimum: 6 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  # para el manejo de sesiones                  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
end

app/models/workshop_car.rb
class WorkshopCar < ActiveRecord::Base
  belongs_to :car
  has_many :stock_spare_parts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Combinación de Correo y Contraseña incorrecta'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/spare_parts_controller.rb
class SparePartsController < ApplicationController
  def new
    @spare_part = SparePart.new
  end

  def create
    @spare_part = SparePart.new(spare_part_params)
    if @spare_part.save
      flash[:success] = "Refaccion Guardada con Exito"
      @spare_parts = SparePart.all

      render 'index'
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def index
    @spare_parts = SparePart.all
  end

  def spare_part_params
      params.require(:spare_part).permit(:brand, :car, :generation, :region, :year, :name, :kind)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def preoperation
  end

  def operation
  end

  def administration
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    #crea un usuario
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "¡Bienvenido a Talleres Syrat!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Datos Actualizados"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :lastname, :email, :permissions, :password,
                                   :password_confirmation)
    end

    def signed_in_user
      redirect_to signin_url, notice: "Por favor inicie sesión" unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # def correct_user
    #   @user = User.find(params[:id])
    #     if !current_user?(@user) || @user.permissions == 1
    #       puts current_user?(@user)
    #     else
    #       redirect_to(root_url)
    #     end
    # end



end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Talleres Syrat"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = { value:   remember_token,
                             expires: 1.day.from_now.utc }
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/spare_parts_helper.rb
module SparePartsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/new.html.erb
<h1>Cars#new</h1>
<p>Find me in app/views/cars/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>

    <a href="#">Syrat</a>
    by Fancy Bear
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href='#'>News</a></li>
    </ul>
  </nav>
</footer>

    Información
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca",   '#' %></li>
      <li><%= link_to "Contacto", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", '#' %></li>
          <li><%= link_to "Help", '#' %></li>

      <%= link_to "Talleres Syrat", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", '#' %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Editar", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Cerrar Sesión", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Iniciar Sesión", signin_path %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>

</header>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>

  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>


  </head>
<body class= "background">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors_messages.html.erb
<% if @spare_part.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@spare_part.errors.count, "error") %>.
    </div>
    <ul>
    <% @spare_part.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/spare_parts/_form.html.erb
    <%= form_for(@spare_part) do |f| %>
      <%= render 'shared/errors_messages' %>

    <div class="form-group">
      <!-- <%= f.label :brand, "Marca" %> -->
      <%= f.text_field :brand, :placeholder => "Marca", :class => 'form-control' %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :car, "Carro" %> -->
      <%= f.text_field :car, :placeholder => "Carro", :class => 'form-control' %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :generation, "Generación" %> -->
      <%= f.text_field :generation, :placeholder => "Generación", :class => 'form-control'  %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :region, "Region" %> -->
      <%= f.text_field :region, :placeholder => "Region", :class => 'form-control'  %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :year, "Año" %> -->
      <%= f.text_field :year, :placeholder => "Año", :class => 'form-control' %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :name, "Nombre" %> -->
      <%= f.text_field :name, :placeholder => "Nombre", :class => 'form-control'  %>
    </div>

    <div class="form-group">
      <!-- <%= f.label :type, "Tipo" %> -->
      <%= f.text_field :kind, :placeholder => "Tipo", :class => 'form-control'  %>
    </div>

      <%= f.submit "Guardar", :class => 'btn btn-default'%>
    <% end %>

app/views/spare_parts/_spare_part.html.erb
<tr>
  <td>
    <%= label, spare_part.name =%>
    <%= label spare_part.brand =%>

  </td>
</tr>

app/views/spare_parts/edit.html.erb
<h1>SpareParts#edit</h1>
<p>Find me in app/views/spare_parts/edit.html.erb</p>

app/views/spare_parts/index.html.erb
<h2>Refacciones</h2>

<% @spare_parts.each do |spare_part| %>
    <li>
      <%= link_to spare_part.name, spare_part %>
    </li>
  <% end %>

app/views/spare_parts/new.html.erb
<h2>Registrar Nuevas Refacciones</h2>

<%= render 'form' =%>

app/views/spare_parts/show.html.erb
<h1>SpareParts#show</h1>
<p>Find me in app/views/spare_parts/show.html.erb</p>

app/views/static_pages/administration.html.erb
<h1>StaticPages#administration</h1>
<p>Find me in app/views/static_pages/administration.html.erb</p>

app/views/static_pages/index.html.erb
<div class="center hero-unit">

    <h1>Fancy Bear</h1>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <h2>
  La home page
  </h2>
  <%= link_to "Dar de Alta Usuario", '#', class: "btn btn-large btn-primary" %>
  <%= link_to "Dar de Alta Pieza", '#', class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), '#' %>



  <h1>Sistema de Administración Talleres Syrat</h1>

  <h2>
    Inicio
  </h2>

  <%= link_to "Dar de Alta Usuario", signup_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Dar de Alta Pieza", new_spare_part_path, class: "btn btn-large btn-primary" %>

</div>

app/views/static_pages/operation.html.erb
<h1>StaticPages#operation</h1>
<p>Find me in app/views/static_pages/operation.html.erb</p>

app/views/static_pages/preoperation.html.erb
<h1>StaticPages#preoperation</h1>
<p>Find me in app/views/static_pages/preoperation.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Editar Usuario") %>
<h1>Actualizar Datos del Usuario</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :lastname, "Apellidos" %>
      <%= f.text_field :lastname %>

      <%= f.label :email, "Correo Electrónico" %>
      <%= f.text_field :email %>

      <%= f.label :permissions, "Permisos" %>
      <%= f.text_field :permissions %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation,"Confirmación de Contraseña" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Guardar Cambios", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Alta de Usuarios') %>
<h1>Dar de Alta</h1>
<p>Llena los datos del nuevo usuario</p>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.label :lastname,"Apellidos" %>
      <%= f.text_field :lastname %>

      <%= f.label :email,"Correo Electrónico" %>
      <%= f.text_field :email %>

      <%= f.label :permissions, "Permisos" %>
      <%= f.text_field :permissions %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation,"Confirmación de Contraseña" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Crear Usuario", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name + " " + @user.lastname %></h1>